### ISSUE TITLE
Removing test using "Ctrl+A" + "Escape" issue

### ISSUE THREAD

**Issue by ArtemNaboka** [petr-konopelko/ng-remote-autocomplete#2]
If input text is removed by "Ctrl+A" + "Escape" key combination and enter is pressed, then search term is still equal to the previous value.

**Comment by petro-konopelko** [comment]
The escape button doesn't clear input text. Could you please explain your case in more details?

**Comment by petro-konopelko** [comment]
Closing. If you still have a problem feel free to contact
