### ISSUE TITLE
Default input autocomplete from browser

### ISSUE THREAD

**Issue by AntonSierikov** [petr-konopelko/ng-remote-autocomplete#6]
Component has input element that has an “autocomplete” attribute with a default value of true. Eventually, input can open two autocomoplete drop-down lists. 
See. 
![image](https://user-images.githubusercontent.com/34750259/53691967-b4d5b480-3d90-11e9-8c39-2409b9e557b0.png)
Please, fix

**Comment by petro-konopelko** [comment]
Please try to use [v1.1.2](https://github.com/petr-konopelko/ng-remote-autocomplete/releases/tag/v1.1.2). I've added it there.
When you try and it works, please close the issue. 
Otherwise please let me know what is wrong.
